#!/usr/bin/env python3
"""Writes lib/pipeline/bundle.c3: the plugin files the `llm` library carries.

A program that links the library runs pipelines without a plugins folder of its
own: `pipeline::extract` writes these files out once and points the runtime at
them. Run this after changing anything under the bundled plugin folders:

    tools/bundle_plugins.py [plugin ...]     # default: kimodo (crig links it; unimate is run from plugins/)

`plugins/lib` is always bundled; it is what every plugin imports.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLUGINS = os.path.join(ROOT, "plugins")
OUT = os.path.join(ROOT, "lib", "pipeline", "bundle.c3")

names = sys.argv[1:] or ["kimodo"]
files = []
for folder in ["lib"] + names:
    base = os.path.join(PLUGINS, folder)
    if not os.path.isdir(base):
        sys.exit(f"no plugin folder {base}")
    for directory, _, entries in os.walk(base):
        for entry in entries:
            if entry.endswith((".js", ".shady", ".json", ".glb", ".txt")):
                files.append(os.path.relpath(os.path.join(directory, entry), PLUGINS))
files.sort()

lines = [
    "// Generated by tools/bundle_plugins.py - do not edit. The plugin files the",
    f"// library carries: plugins/lib and {', '.join(names)}.",
    "module llm::pipeline;",
    "",
]
for i, rel in enumerate(files):
    lines.append(f'const char[*] BUNDLED_{i} = $embed("../../plugins/{rel}");')
lines += [
    "",
    f"const String[{len(names)}] BUNDLED_PLUGINS = {{ {', '.join(repr(n).replace(chr(39), chr(34)) for n in names)} }};",
    "",
    "fn BundledFile[] bundled_files()",
    "{",
    f"\tstatic BundledFile[{len(files)}] files;",
    "\tfiles = {",
]
for i, rel in enumerate(files):
    lines.append(f'\t\t{{ "{rel}", (char[])BUNDLED_{i}[..] }},')
lines += ["\t};", "\treturn files[..];", "}", ""]

with open(OUT, "w") as out:
    out.write("\n".join(lines))
print(f"{OUT}: {len(files)} files")
